import type { NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import QueueCard from "~/components/QueueCard";

const Home: NextPage = () => {
  const queueQuery = api.queue.all.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div className="container mt-12 flex flex-col items-center justify-center gap-4 px-4 py-8">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            Create <span className="text-pink-400">T3</span> Turbo
          </h1>

          {queueQuery.data ? (
            <div className="w-full max-w-2xl">
              {queueQuery.data?.length === 0 ? (
                <span>There are no queues!</span>
              ) : (
                <div className="flex h-[40vh] justify-center overflow-y-scroll px-4 text-2xl">
                  <div className="flex w-full flex-col gap-4">
                    {queueQuery.data?.map((p) => {
                      return <QueueCard key={p.id} queue={p} />;
                    })}
                  </div>
                </div>
              )}
            </div>
          ) : (
            <p>Loading...</p>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
