import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Queue from "./components/queue";

import { api, type RouterOutputs } from "~/utils/api";
import Sidebar from "./components/sidebar";

/*
const PostCard: React.FC<{
  post: RouterOutputs["post"]["all"][number];
  onPostDelete?: () => void;
}> = ({ post, onPostDelete }) => {
  return (
    <div className="rounded-lg flex flex-row bg-white/10 p-4 transition-all hover:scale-[101%]">
      <div className="flex-grow">
        <h2 className="font-bold text-2xl text-pink-400">{post.title}</h2>
        <p className="mt-2 text-sm">{post.content}</p>
      </div>
      <div>
        <span
          className="cursor-pointer font-bold text-sm text-pink-400 uppercase"
          onClick={onPostDelete}
        >
          Delete
        </span>
      </div>
    </div>
  );
};
*/

/*

const CreatePostForm: React.FC = () => {
  const utils = api.useContext();

  const [title, setTitle] = useState("");
  const [content, setContent] = useState("");

  const { mutate, error } = api.post.create.useMutation({
    async onSuccess() {
      setTitle("");
      setContent("");
      await utils.post.all.invalidate();
    },
  });

  return (
    <div className="flex flex-col w-full max-w-2xl p-4">
      <input
        className="rounded bg-white/10 text-white mb-2 p-2"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        placeholder="Title"
      />
      {error?.data?.zodError?.fieldErrors.title && (
        <span className="mb-2 text-red-500">
          {error.data.zodError.fieldErrors.title}
        </span>
      )}
      <Link href="/yoo">Hello</Link>
      <input
        className="rounded bg-white/10 text-white mb-2 p-2"
        value={content}
        onChange={(e) => setContent(e.target.value)}
        placeholder="Content"
      />
      {error?.data?.zodError?.fieldErrors.content && (
        <span className="mb-2 text-red-500">
          {error.data.zodError.fieldErrors.content}
        </span>
      )}
      <button
        className="rounded font-bold bg-pink-400 p-2"
        onClick={() => {
          mutate({
            title,
            content,
          });
        }}
      >
        Create
      </button>
    </div>
  );
};
*/

const Home: NextPage = () => {
  /*
  const postQuery = api.post.all.useQuery();
  */

  /*
  const deletePostMutation = api.post.delete.useMutation({
    onSettled: () => postQuery.refetch(),
  });
  */

  return <Queue></Queue>;
  /*
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-b flex flex-col h-screen from-[#2e026d] to-[#15162c] text-white items-center">
        <div className="container flex flex-col mt-12 py-8 px-4 gap-4 items-center justify-center">
          <h1 className="font-extrabold tracking-tight text-5xl sm:text-[5rem]">
            Create <span className="text-pink-400">T3</span> Turbo
          </h1>

          <CreatePostForm />

          {postQuery.data ? (
            <div className="w-full max-w-2xl">
              {postQuery.data?.length === 0 ? (
                <span>There are no posts!</span>
              ) : (
                <div className="flex h-[40vh] px-4 text-2xl justify-center overflow-y-scroll">
                  <div className="flex flex-col w-full gap-4">
                    {postQuery.data?.map((p) => {
                      return (
                        <PostCard
                          key={p.id}
                          post={p}
                          onPostDelete={() => deletePostMutation.mutate(p.id)}
                        />
                      );
                    })}
                  </div>
                </div>
              )}
            </div>
          ) : (
            <p>Loading...</p>
          )}
        </div>
      </main>
    </>
  );
  */
};

export default Home;
